site_name: Python Unterlagen

theme:
  name: material
  language: de

nav:
  - Cheatsheet: cheatsheet.md
  - Start: index.md
  - Einführung: einfuehrung.md
  - Variablen: variablen-und-datentypen.md
  - Schleifen: schleifen.md
  - Funktionen ohne Rückgabewert: funktionen-ohne-rueckgabewert.md
  - Bedingungen: bedingungen.md
  - Verzweigung: verzweigung.md
  - Flussdiagramme: flussdiagramme.md
  - while-Schleife: while-schleife.md
  - Funktionen mit Rückgabewert: funktionen.md
  - Listen: listen.md
  - Dictionaries: dictionaries.md

  
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css