name: PDFs erstellen

on:
  push:
    branches:
      - main
    paths:
      - "docs/**/*.md"
      - ".github/workflows/build-pdf.yml"

  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: Pandoc installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Typst installieren
        run: |
          wget -q https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/typst

      - name: PDF-Ordner erstellen
        run: mkdir -p pdf

      - name: Einführung als PDF erstellen
        run: |
          pandoc docs/einfuehrung.md \
            -o pdf/einfuehrung.pdf \
            --pdf-engine=typst \
            --toc \
            -V papersize=a4 \
            -V margin=2cm

      - name: PDFs speichern
        uses: actions/upload-artifact@v4
        with:
          name: Python-Skript-PDF
          path: pdf/